services:
  embytoalist:
    image: ghcr.io/zsbai/embytoalist:latest
    volumes:
      - ./config.py:/app/config.py
      - /path/to/cache_dir:/path/to/cache_dir
    # host和port二选一
    network_mode: host
    # ports:
    #   - 60001:60001
    restart: unless-stopped
